languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Kevin Atkins"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Software Developer"

[params.author]
  name = "Kevin Atkins"
  image = "img/portrait.png"
  headline = "Software Developer"
  bio = "A little bit about you"
  links = [
  { github = "https://github.com/atkinkev" },
  { linkedin = "https://linkedin.com/in/kevin-atkins-522523166" }
  ]
